version: "3"

services:
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=/*DB Name*/
    volumes:
      - ./docker_data/postgres-data:/var/lib/postgresql/data
  # redis:
  #   image: "redis:alpine"
  #   volumes:
  #     - ./docker_data/redis/redis-data:/var/lib/redis
  #     - ./docker_data/redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   ports:
  #     - "6379:6379"
